name = "playground"
version = "0.1.0"
defaultTargets = ["playground"]

[[lean_lib]]
name = "Playground"

[[require]]
name = "REPL"
git = "https://github.com/leanprover-community/repl.git"
rev = "master"
version = "v4.22.0-rc4"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"
version = "v4.22.0-rc4"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop.git"
rev = "master"
version = "v4.22.0-rc4"
